########################################################################
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
########################################################################

#———————————————————————————————————————————————————————————————————————————————————————
#Security-Driven Cloud Acceleration Template Stack For KMS
#Author: Christopher Rae (xrae@amazon.com)
#Date: March 1st, 2023
#———————————————————————————————————————————————————————————————————————————————————————

AWSTemplateFormatVersion: "2010-09-09"


#———————————————————————————————————————————————————————————————————————————————————————
#Configure Conformance Packs To Enable Security and Privacy Best Practices As Part of Nested Stack
#———————————————————————————————————————————————————————————————————————————————————————
#---Configure AWS Foundational Security Best Practices (FSBP)
#———————————————————————————————————————————————————————————————————————————————————————
#[INSERT THIS]https://github.com/awslabs/aws-config-rules/blob/master/aws-config-conformance-packs/Operational-Best-Practices-for-Security-Services.yaml
#[INSERT THIS]https://github.com/awslabs/aws-config-rules/blob/master/aws-config-conformance-packs/Operational-Best-Practices-for-Encryption-and-Keys.yaml
#[INSERT THIS] https://github.com/awslabs/aws-config-rules/blob/master/aws-config-conformance-packs/Security-Best-Practices-for-AWS-WAF.yaml

#———————————————————————————————————————————————————————————————————————————————————————
#---Setup Center for CISA Cyber Fundamentals 
#———————————————————————————————————————————————————————————————————————————————————————
#[INSERT THIS]https://github.com/awslabs/aws-config-rules/blob/master/aws-config-conformance-packs/Operational-Best-Practices-for-CISA-Cyber-Essentials.yaml

#———————————————————————————————————————————————————————————————————————————————————————
#---Setup Center for Internet Security (CIS) AWS Foundations Benchmark v1.4.0
#———————————————————————————————————————————————————————————————————————————————————————
#[INSERT THIS]https://github.com/awslabs/aws-config-rules/blob/master/aws-config-conformance-packs/Operational-Best-Practices-for-CIS-AWS-v1.4-Level2.yaml

#———————————————————————————————————————————————————————————————————————————————————————
#---Configure PCI Standard Best Practices 
#———————————————————————————————————————————————————————————————————————————————————————
#[INSERT THIS]https://github.com/awslabs/aws-config-rules/blob/master/aws-config-conformance-packs/Operational-Best-Practices-for-PCI-DSS.yaml

#———————————————————————————————————————————————————————————————————————————————————————
#---Setup NIST 800-53 rev 5 Security Standards
#———————————————————————————————————————————————————————————————————————————————————————
#[INSERT THIS]https://github.com/awslabs/aws-config-rules/blob/master/aws-config-conformance-packs/Operational-Best-Practices-for-NIST-800-53-rev-5.yaml)

#———————————————————————————————————————————————————————————————————————————————————————
#---Setup NIST Privacy Framework 1.0 Security Standards
#———————————————————————————————————————————————————————————————————————————————————————
#[INSERT THIS] https://github.com/awslabs/aws-config-rules/blob/master/aws-config-conformance-packs/Operational-Best-Practices-for-NIST-Privacy-Framework.yaml


#———————————————————————————————————————————————————————————————————————————————————————
# Enable KMS & Configure Best Practices
#———————————————————————————————————————————————————————————————————————————————————————
Type: AWS::KMS::Key
Properties: 
  Description: String
  Enabled: true
  EnableKeyRotation: true
  KeyPolicy: Json
  KeySpec: String
  KeyUsage: String
  MultiRegion: False
  PendingWindowInDays: 30
  Tags: "SDCA"

# Configure AWS Config Conformance Pack Solution
      - parameter_key: pDeployConfigConformancePackSolution
        parameter_value: 'Yes'
      - parameter_key: pConformancePackName
        parameter_value: 'sra-operational-best-practices-for-encryption-and-keys'
      - parameter_key: pConformancePackTemplateName
        parameter_value: 'Operational-Best-Practices-for-Encryption-and-Keys.yaml'
      - parameter_key: pDeliveryS3KeyPrefix
        parameter_value: ''
      - parameter_key: pConformancePackExcludedAccounts
        parameter_value: ''

#——————————————————————————————————————————————————
# Define and Enable Push Notifications
#——————————————————————————————————————————————————
#Subscribe to AWS Security Hub announcements with Amazon Simple Notification Service (SNS)
#Configure AWS Lambda Functions
#Set Email Alerts
#——————————————————————————————————————————————————
